// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type GetUsersResponse struct {
	Results []*User `json:"results"`
	Total   int     `json:"total"`
}

type NewUser struct {
	Msisdn    string `json:"msisdn"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Email     string `json:"email"`
	Login     string `json:"login"`
	Passwd    string `json:"passwd"`
}

type User struct {
	ID        string `json:"id"`
	Msisdn    string `json:"msisdn"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Email     string `json:"email"`
}
